[project]
name = "decrypto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "fastapi[standard]>=0.122.0",
  "itsdangerous>=2.2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
